### ISSUE TITLE
Update ServiceIntentRequest model for NBI

### ISSUE THREAD

**Issue by disprosium8** [sdn-sense/sense-o-py-client#2]
* [ ] 1a. Make SENSE API intent format consistent with StackV-Service profile format (DNC for now)
Swagger doc upgrade 2.0

----
**Original:** 
Trying to request similar intent that is available via StackV webUI but through REST API.  Using service request model as documented at https://app.swaggerhub.com/apis/xi-yang/SENSE-O-Intent-API/1.0.0#/connection/post_service

Would like to request similar intent via API.

```
intent = {
    "service_type": "Multi-Path P2P VLAN",
    "service_alias": "DTNaaS-CERN-3989-API",
    "ip_ranges": [
        {
            "start": "10.4.44.101/24",
            "end": "10.4.44.102/24"
        }
    ],
    "connections": [
        {
            "bandwidth": {
                "qos_class": "guaranteedCapped",
                "capacity": "1000"
            },
            "name": "Connection 1",
            "terminals": [
                {
                    "vlan_tag": "3989",
                    "assign_ip": False,
                    "uri": "urn:ogf:network:cern.ch:2013:s0:1_1:production7"
                },
                {
                    "vlan_tag": "3989",
                    "assign_ip": False,
                    "uri": "urn:ogf:network:cern.ch:2013:cixp-surfnet-dtn.cern.ch"
		}
            ]
	}
    ]
}


endpoint = '/sense/service'
url = f"{api_url}{endpoint}"
api_call_headers.update({"Content-type": "application/json"})
res = requests.post(url, headers=api_call_headers, verify=False, data=json.dumps(intent))
print (res.text, res.status_code)
print ('='*100)
```

Results in

```
Unrecognized field &quot;vlan_tag&quot; (class net.maxgigapop.mrs.rest.api.model.sense.ServiceTerminationPoint), not marked as ignorable 400
```

**Comment by juztas** [comment]
That looks to be an Orchestrator issue, not py client (even py-client is not yet in use). @xi-yang

**Comment by xi-yang** [comment]
@disprosium8 There are subtle difference in the JSON format between the SENSE NBI intent and StackV intent. Here is an example  SENSE intent. We will consider normalizing the two schemas to eliminate the difference. 

```
{
  "service_type": "Multi-Path P2P VLAN",
  "service_alias": "Demo.L2.MAX-Caltech-via-iCair-3613",
  "connections": [
    {
      "name": "connection 1",
      "terminals": [
        {
          "uri": "urn:ogf:network:maxgigapop.net:2013:180-134.research.maxgigapop.net",
          "label": "3613",
          "assign_ip": true
        },
        {
          "uri": "urn:ogf:network:ultralight.org:2013:sdn-dtn-1-7.tier2",
          "label": "3613",
          "assign_ip": true
        }
      ],
      "bandwidth": {
         "qos_class": "guaranteedCapped",
         "capacity": "1000"
      },
      "path_profile": {
        "inclusion_list": [
           {
              "uri": "urn:ogf:network:slqfx3500.icair.org:2013:topology"
           }

        ]
      }
    }
  ],
  "ip_ranges": [
    {
      "start": "172.31.11.1/24",
      "end": "172.31.11.2/24"
    }
  ]
}

```

**Comment by disprosium8** [comment]
Ah, good to know.  I wasn't sure if `label` was vlan id/tag based on the model.  This should work then now that I understand the mapping.

```
ServiceTerminationPoint
type | string
-- | --
uri | string
label | string
ipv4_prefix_list | string
assign_ip | boolean

```

**Comment by xi-yang** [comment]
The raw intent REST API does not have a data schema binding and the SENSE REST API does. They are implemented differently and thus the discrepancy. Let's leave this issue open as a reminder that we will make them compatible in the future.

**Comment by xi-yang** [comment]
This issue now tracks the sub-task 1a in https://github.com/sdn-sense/sense-o-py-client/issues/1#issuecomment-799538365

* [ ] 1a. Make SENSE API intent format consistent with StackV-Service profile format (DNC for now)
Swagger doc upgrade 2.0

**Comment by xi-yang** [comment]
@R-Jimenez I am thinking of take the intent input from SENSE service API without JavaX binding, and then use your JSON intent validator to check it. Is this doable?

**Comment by xi-yang** [comment]
> @R-Jimenez I am thinking of take the intent input from SENSE service API without JavaX binding, and then use your JSON intent validator to check it. Is this doable?

Never mind. On a second thought, I think I will stay with the JAXB for the schema validation.  It will be a good idea to clearly define the schema in the swagger API doc. Meanwhile, I understand the current frontend code does the validation only at the JavaScript level although we had discussion about pushing some of such validation to the Java level.

**Comment by R-Jimenez** [comment]
I will be building a JSON Schema for my endpoints, so you can evaluate my approach there and decide to convert if you'd like. There should be a JSON schema validator somewhere on maven.

Additionally I did some more work last night on design and have come to the conclusion that for structure and stability I will be building POJO bindings for Frontend entities to use with Gson parsing.
