### ISSUE TITLE
Cancel call is allowed upon Cancel - READY status

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/sense-o-py-client#21]
This is partly a StackV issue as the API endpoint should check and disallow this. 

The client should also check and put some guardrail code here.

**Comment by R-Jimenez** [comment]
Is simple to pull in some basic logic from the portal in this case. I already have some helpers to verify service status and can throw a standard 400 error in such cases.

**Comment by xi-yang** [comment]
Taken care of from the server side.
