### ISSUE TITLE
Possible to reserve/commit service that is in CANCEL-READY via NBI?

### ISSUE THREAD

**Issue by disprosium8** [sdn-sense/sense-o-py-client#3]
Track sub task 4a of #1 
* [ ] 4a. Document extra /sevice and /instance resources as needed
- force_cancel, force_retry, verify etc. (as incorporated into API client packages)

Also refer to #11 for potential change of plan.

---
**Original:**

Attempting to re-initialize an existing service after terminate or cancel.  Release/terminate on READY service does work via NBI, but can't force re-init or reinstate afterwards.  Is there a way to do this?

```
endpoint = '/sense/service/89239501-d8c0-4f14-97fa-2c0a9afc0dce/reserve'
url = f"{api_url}/{endpoint}"
res = requests.put(url, headers=api_call_headers, verify=False)
print (res.text, res.status_code)
print ('='*100)
```

```
Request unacceptable under status:CANCEL - READY
```

**Comment by xi-yang** [comment]
All operations are not exposed to SENSE NBI. But you can use the raw service API. Refer to: https://github.com/xi-yang/StackV.devops/tree/master/testing/scripts

To force retry:

`PUT /service/$SVC_INSTANCE_ID/propagate_forcedretry ` then `PUT https://github.com/xi-yang/StackV.devops/blob/master/testing/scripts/forceretry.sh`

A new version of code will expose internal exception messages to the REST response body. I hope the client lib can interpret those and provide more meaningful feedback upon failures.
