### ISSUE TITLE
[SENSE-O API] Get all edgepoints

### ISSUE THREAD

**Issue by juztas** [sdn-sense/sense-o-py-client#7]
Need call to get list of all edge points, like: 
https://sense-o.es.net:8443/StackV-web/restapi/discovery/edgepoints

**Comment by xi-yang** [comment]
With the end-site model change, we need to update the SPARQL for endpoints. 

@juztas My understanding of the model change is that we will have up to three scenario:
1. Each DTN host interface peers directly with a WAN domain port 
2. DTN host interface(s) peer with one VSW and one VSW peers with a WAN domain port
3. DTN host interface(s) peer with separate VSWs and multiple VSWs peer with WAN domain(s) / port(s) 

There could even to be mixed 1, 2, 3 ?

We will need more complex SPARQL when listing the endpoints.
