### ISSUE TITLE
API methods for service profile and service intent

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/sense-o-py-client#9]
This issue tracks the development of API methods for _Service Profile_ and _Service Intent_ in #1.

Service Profile - the intent "template" one (often admin) defines and store through web UI. It is not associated with a specific service instance.

Service Intent - the intent "instance" associated with a specific service instance. A service instance can have multiple "versions" or instances of service intent (identified by UUID). Each version can source from a predefined template (service profile). 

* [x] 1b. List / Describe service profiles - create from UI and read-only for API
   * @R-Jimenez we may need to change the int id into UUID for profile now, or live with int forever. 
   * All JSON formatted.
   * List will not include profile text and Describe call does

* [x] 1c. List / Describe "service intent" versions
   * A "service instance" UUID is provided for working with "service intent"
   * All JSON formatted.
   * List will not include profile text and Describe call does

**Comment by R-Jimenez** [comment]
B: 
* It makes sense to me to unify our ID structures into UUIDs, I agree. 
* Do you mean to store the data itself in DB in JSON, or simply to have a proper class for consistent JSON object mapping?
* Fair, only requires small change to current API.

C:
* Intents are already attached, and query in the PM already exists for finding by instance, good here.
* Same question as above for B.
* For the listing endpoint, I assume we'll still retrieve the remaining metadata (instance and delta IDs, creation time, provisioned).

**Comment by xi-yang** [comment]
> B:
> 
> * Do you mean to store the data itself in DB in JSON, or simply to have a proper class for consistent JSON object mapping?
> 
> C:
> 
> * Same question as above for B.


Meant to have API response in JSON format when representing list or single view of profile / intent. I guess that was what you planned to do anyways.

**Comment by R-Jimenez** [comment]
Yes, there will be a new APICommon response structure similar to how I standardized the error responses. All v2 endpoints will have a standardized output (for now loosely following https://jsonapi.org/format) that tentatively looks like the following:
```
{
  "links": {
    "self": "http://localhost/StackV-web/restapi/logging/logs"
  },
  "data": [
    {
      // log object
    },
    ...
  ]
}
```
Error responses will likely also get a bit more standardized as I have a better idea of best practices now for the request layer.

**Comment by xi-yang** [comment]
Let's put all the related new development into the `StackV/ Feature-sense_nbi_rework-M11-xyang` branch.

**Comment by R-Jimenez** [comment]
I have 1b staged and functionally implemented and ready for testing with the new data structure, cleaner object mapping, and new generic access control, but I have a question on priorities and documentation. Would you like me to spend some time for each of these API expansion tasks to do the documentation as I go along each endpoint, or would you rather me just do the implementation, and hold off on documentation until the end of each issue? Happy to do either, would understand both approaches, just a matter of if you wanted certain things online sooner or later.
